(45%) Look for the multiclass classifiers in Logistic Regression, 𝑘-Nearest Neighbors and Support Vector Machine. Apply them to analyze AutoMPG and discuss the results. The target is to classify the “origin” of the car and “mpg” can be included in the X.

In [ ]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.linear_model import LogisticRegression 
from sklearn import svm
from sklearn.metrics import confusion_matrix


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/homework_7/auto-mpg.csv', sep=";", header=None, names=['Mpg', 'Cylinders', 'Displacement' ,'Horsepower', 'Weight', 'Acceleration', 'Model year', 'Origin', 'Car name'])


df.head()

Mpg  Cylinders  Displacement  Horsepower  Weight  Acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   Model year  Origin                   Car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino

In [ ]:
# X and y
X = df [['Cylinders', 'Displacement' ,'Horsepower', 'Weight', 'Acceleration', 'Model year', 'Mpg']]
y = df[['Origin']]
len(y)

392

Normalize the data because we are working with different types of data.


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Normalize
sc=StandardScaler()
sc.fit(X_train)
X_train_nor=sc.transform(X_train)
X_test_nor=sc.transform(X_test)

Logistic Regression

In [ ]:
LR = LogisticRegression( multi_class='multinomial' )
LR.fit(X_train, y_train)
predictions_LR = LR.predict(X_test)
print("LR preductions: ", predictions_LR)
print("LR accuracy: ", 100*LR.score(X_test, y_test),"%")
conf_mat_LR = confusion_matrix(y_test, predictions_LR)
print("LR confusion matrix:")
print(conf_mat_LR)



LR preductions:  [3 1 1 1 3 1 3 2 1 3 1 1 1 1 1 3 3 1 3 1 1 1 1 1 3 1 1 1 1 1 1 2 1 3 1 1 3
 1 1 1 1 3 1 1 3 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 3 3 1 2 1 1 2 2 3 3 3 1 1
 1 1 3 1 3]
LR accuracy:  74.68354430379746 %
LR confusion matrix:
[[46  1  3]
 [ 3  4  8]
 [ 4  1  9]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


K-Nearest Neighbor

In [ ]:
KNN = KNeighborsClassifier(n_neighbors = 3)
KNN.fit(X_train,y_train)
predictions_KNN = KNN.predict(X_test)
print("KNN preductions: ", predictions_KNN)
print("KNN accuracy: ",100*KNN.score(X_test, y_test),"%")
conf_mat_KNN = confusion_matrix(y_test, predictions_KNN)
print("KNN confusion matrix:")
print(conf_mat_KNN)


KNN preductions:  [1 1 1 1 3 1 3 2 1 3 2 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 1 1 3
 1 1 1 1 1 3 1 2 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 3 1 2 1 1 1 2 1 1 1 1 1
 3 1 3 1 1]
KNN accuracy:  75.9493670886076 %
KNN confusion matrix:
[[48  0  2]
 [ 4  7  4]
 [ 9  0  5]]


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Support Vector Machine

In [ ]:
SVM = svm.SVC(kernel='linear',C=1)
SVM.fit(X_train,y_train)
predictions_SVM = SVM.predict(X_test)
print("SVM preductions: ", predictions_SVM)
print("SVM accuracy: ",100*SVM.score(X_test, y_test),"%")
conf_mat_SVM = confusion_matrix(y_test, predictions_SVM)
print("SVM confusion matrix:")
print(conf_mat_SVM)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM preductions:  [2 1 1 3 3 1 3 2 1 3 1 1 1 1 1 3 3 1 3 1 1 1 1 1 3 1 1 1 1 1 2 1 2 2 1 1 3
 1 1 1 1 3 1 1 3 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 2 3 1 2 1 1 3 2 3 1 1 1 1
 1 1 2 1 1]
SVM accuracy:  75.9493670886076 %
SVM confusion matrix:
[[46  2  2]
 [ 2  7  6]
 [ 6  1  7]]


Conclusion: 

All of them had the similar accuracy related to the predictions. Different results can be obtained if we change the parameters that we will use to fit the machine learning algorithm. Also, we need to standardize the data first because we are going on with different kinds of data. 